apiVersion: v1
kind: ConfigMap
metadata:
  name: gesture-recognizier
  namespace: default
data:
  recognizier: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_uri": "http://zipkin.default:9411",
      "group_ids": [
        0
      ]
    }

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "is-gesture-recognizier"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: recognizier
    spec:
      containers:
        - name: service
          image: luizcarloscf/is-gesture-recognizier:0.0.1
          command: ["python3"]
          args: ["src/is_gesture_recognizier/main.py", "/conf/options.json"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 2048Mi
              nvidia.com/gpu: 1
          volumeMounts:
            - name: options
              mountPath: /conf/
      volumes:
        - name: options
          configMap:
            name: gesture-recognizier
            items:
              - key: recognizier
                path: options.json
