---
apiVersion: v1
kind: ConfigMap
metadata:
  name: is-gesture-recognizer
  namespace: default
data:
  recognizier: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_uri": "http://zipkin.default:9411",
      "group_ids": [
        0
      ],
      "period": 5
    }

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: is-gesture-recognizer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: is-gesture-recognizer
    spec:
      containers:
        - name: is-gesture-recognizer
          image: luizcarloscf/is-gesture-recognizer:0.0.1
          #command: ["sleep"]
          #args: ["30000000"]
          command: ["python3"]
          args: ["src/is_gesture_recognizer/main.py", "/conf/options.json"]
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 30
          resources:
            limits:
              cpu: "1"
              memory: 2048Mi
              nvidia.com/gpu: 1
          volumeMounts:
            - name: options
              mountPath: /conf/
      volumes:
        - name: options
          configMap:
            name: is-gesture-recognizer
            items:
              - key: recognizier
                path: options.json

---
apiVersion: v1
kind: Service
metadata:
  name: is-gesture-recognizer
  labels:
    app: is-gesture-recognizer
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: is-gesture-recognizer

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: is-gesture-recognizer
  labels:
    app: is-gesture-recognizer
spec:
  selector:
    matchLabels:
      app: is-gesture-recognizer
  endpoints:
    - port: web
      interval: 5s # scrape the endpoint every X seconds

